#!/bin/bash

PARENT_FOLDER=".."
INSTALL_FOLDER="zTeX_TDS"
EXTRACT_FOLDER="$PARENT_FOLDER/$INSTALL_FOLDER"
BUNDLE_DOC_FOLDER="$EXTRACT_FOLDER/ztex_bundle_docs"
TARGET_FOLDER_SOLARIS="$HOME/texmf/tex/latex/ztex"     # for Solaris
TARGET_FOLDER_DARWIN="$HOME/texmf/tex/latex/ztex"      # for MacOS
TARGET_FOLDER_LINUX="$HOME/texmf/tex/latex/ztex"       # for Linux
TARGET_FOLDER_BSD="$HOME/texmf/tex/latex/ztex"         # for BSD
TARGET_FOLDER_WIN="/mnt/c/Users/$WIN_USER_NAME/texmf/tex/latex/ztex"  # for Windows


# util functions:
RED="\033[31m"
YELLOW="\033[33m"
GREEN="\033[32m"
RESET="\033[0m"
print_info() {
    # printf "\n"
    printf "%b===> INFO:%b %s\n" "$GREEN" "$RESET" "$*" >&1
}
print_warn() {
    # printf "\n"
    printf "%b===> WARNING:%b %s\n" "$YELLOW" "$RESET" "$*" >&2
}
print_err() {
    # printf "\n"
    printf "%b===> ERROR:%b %s\n" "$RED" "$RESET" "$*" >&2
}

# check OS-type
unix_type_invalid() {
    print_err "variable 'OSTYPE' is empty or unset !" 
}
unix_type_valid() {
    print_info "detect platform: '$OSTYPE'."
}
win_user_name_check() {
    if [ -z "$WIN_USER_NAME" ]; then
	print_err "variable 'WIN_USER_NAME' is empty or unset !" 
    else
	print_info "detect windows user name: '$WIN_USER_NAME'."
    fi
}
detect_os() {
    case "$OSTYPE" in
        solaris*) TARGET_FOLDER="$TARGET_FOLDER_SOLARIS" && unix_type_valid;;
        darwin*)  TARGET_FOLDER="$TARGET_FOLDER_DARWIN" && unix_type_valid;;
        linux*)   TARGET_FOLDER="$TARGET_FOLDER_LINUX" && unix_type_valid;;
        msys*)    TARGET_FOLDER="$TARGET_FOLDER_WIN" && win_user_name_check;;
        bsd*)     TARGET_FOLDER="$TARGET_FOLDER_BSD" && unix_type_valid;;
        *)        unix_type_invalid && exit 1;;
    esac
}

usage() {
    echo "This script will generate TDS folder and install it automatically."
    echo "----------------------------------------"
    echo "NOTE:"
    echo "  * For *nix users, check variable 'OSTYPE' first."
    echo "  * For windows users, export variable 'WIN_USER_NAME=<name>' first."
    echo "  * Merge pdf function relies on 'awk', 'tree'(optional), 'pdftk' and 'zsh'."
    echo "----------------------------------------"
    echo ""
    echo "Usage: $0 [-h] [-m] [-d] [-r] [-i]"
    echo "Options:"
    echo "  -h  Show this help message"
    echo "  -e  Extract install folder from project(will call 'merge_docs')"
    echo "  -m  Merge all of the user manuals into one PDF"
    echo "  -d  Delete previous extract folder and '*.tar.gz': '$EXTRACT_FOLDER'"
    echo "  -r  Remove previous zTeX installing folder: '$TARGET_FOLDER'"
    echo "  -i  Copy '$EXTRACT_FOLDER' to '$TARGET_FOLDER'"
    exit 0
}

# extract source code and doc from zTeX
extrac_source () {
    # mkdir
    mkdir -p "$EXTRACT_FOLDER"/zlatex/code
    mkdir -p "$EXTRACT_FOLDER"/ztikz/code
    mkdir -p "$EXTRACT_FOLDER"/ztool/code
    mkdir -p "$EXTRACT_FOLDER"/zslide/code
    mkdir -p "$EXTRACT_FOLDER"/ztex_intro/doc
    mkdir -p "$EXTRACT_FOLDER"/zlatex/doc
    mkdir -p "$EXTRACT_FOLDER"/ztikz/doc
    mkdir -p "$EXTRACT_FOLDER"/ztool/doc
    mkdir -p "$EXTRACT_FOLDER"/zslide/doc

    # merge pdf
    if [ -d "$BUNDLE_DOC_FOLDER" ]; then 
        print_warn "folder '$BUNDLE_DOC_FOLDER' already exsit, give up merge these PDF again."
    else
        merge_docs
    fi

    # copy source files
    cp -r ./zlatex/code/* "$EXTRACT_FOLDER"/zlatex/code
    cp -r ./ztikz/code/*  "$EXTRACT_FOLDER"/ztikz/code
    cp -r ./ztool/code/*  "$EXTRACT_FOLDER"/ztool/code
    cp -r ./zslide/code/* "$EXTRACT_FOLDER"/zslide/code

    # copy user manuals
    cp ./ztex_intro/doc/ztex_intro.pdf "$EXTRACT_FOLDER"/ztex_intro/doc/
    cp ./zlatex/doc/ztex_interface.pdf "$EXTRACT_FOLDER"/zlatex/doc/
    cp ./ztikz/doc/ztikz_interface.pdf "$EXTRACT_FOLDER"/ztikz/doc/
    cp ./ztool/doc/ztool_interface.pdf "$EXTRACT_FOLDER"/ztool/doc/
    cp ./ztikz/doc/ztikz_examples.pdf  "$EXTRACT_FOLDER"/ztikz/doc/
    cp ./zslide/doc/zslide_manual.pdf  "$EXTRACT_FOLDER"/zslide/doc/

    # remove 'auto' folder generated by Emacs
    print_info "removing 'auto' folder generated by Emacs from zTeX TDS ..."
    find "$EXTRACT_FOLDER" -type d -name "auto" -exec rm -rf {} +
    find "$EXTRACT_FOLDER" -type d -name ".auctex-auto" -exec rm -rf {} +

    # compress TDS
    print_info "compressing zTeX TDS for installing ..."
    tar -czvf zTeX_TDS.tar.gz "$EXTRACT_FOLDER"
    mv zTeX_TDS.tar.gz "$PARENT_FOLDER"
    print_info "zTeX TDS extract successfully, see folder: $EXTRACT_FOLDER"
}

# merge these documents into one
merge_docs() {
    # merged bundle doc
    mkdir -p "$BUNDLE_DOC_FOLDER"
    print_info "merging user interface ..."

    # the bundle intro_examples:
    print_info "merging ztex_bundle_example.pdf ..."
    ./merge_pdf.sh ztex_bundle_intro_example.pdf \
        ./ztex_intro/doc/ztex_intro.pdf \
        ./zlatex/doc/ztex_toc_example.pdf \
        ./ztikz/doc/ztikz_examples.pdf
    # the whole bundle:
    print_info "merging ztex_bundle.pdf ..."
    ./merge_pdf.sh ztex_bundle.pdf \
        ./ztex_intro/doc/ztex_intro.pdf \
        ./zlatex/doc/ztex_interface.pdf \
        ./ztool/doc/ztool_interface.pdf \
        ./ztikz/doc/ztikz_interface.pdf \
        ./zlatex/doc/ztex_toc_example.pdf \
        ./ztikz/doc/ztikz_examples.pdf
    # the bundle interface
    print_info "merging ztex_bundle_interface.pdf ..."
    ./merge_pdf.sh ztex_bundle_interface.pdf \
        ./zlatex/doc/ztex_interface.pdf \
        ./ztool/doc/ztool_interface.pdf \
        ./ztikz/doc/ztikz_interface.pdf

    # move these merged PDFs to BUNDLE_DOC_FOLDER
    mv ./ztex_bundle_intro_example.pdf "$BUNDLE_DOC_FOLDER"
    mv ./ztex_bundle_interface.pdf     "$BUNDLE_DOC_FOLDER"
    mv ./ztex_bundle.pdf               "$BUNDLE_DOC_FOLDER"
}

# handle command line arguments
detect_os
while getopts "hemdri" opt; do
    case $opt in
        h)
            usage
            ;;
        e)
            extrac_source
            ;;
        m) 
            merge_docs
            ;;
        d)
            print_info "directory-'$EXTRACT_FOLDER' and file-'$EXTRACT_FOLDER.tar.gz' have been removed."
            rm -rf "$EXTRACT_FOLDER"
            rm -rf "$EXTRACT_FOLDER.tar.gz"
            exit 0
            ;;
        r)
            if [ -d "$TARGET_FOLDER" ]; then 
                rm -rf "$TARGET_FOLDER"
                print_info "remove previous zTeX installing local folder: '$TARGET_FOLDER'"
	    else
		print_warn "zTeX bundle has been removed or has NOT been installed yet !"
            fi
            ;;
        i)
            if [ ! -d "$EXTRACT_FOLDER" ]; then
                print_err "folder '$EXTRACT_FOLDER' do NOT exsit, run './extract.sh -e' to extract zTeX TDS first!"
                exit 1
            fi
            if [ -d "$TARGET_FOLDER" ]; then 
                rm -rf "$TARGET_FOLDER"
                print_warn "remove previous zTeX installing local folder: '$TARGET_FOLDER'"
            fi
            print_info "installing zTeX to: '$TARGET_FOLDER' ..."
            mkdir -p "$TARGET_FOLDER"
            print_info "zTeX DTS directory structure as follows:"
            ls -l "$EXTRACT_FOLDER"
            cp -r "$EXTRACT_FOLDER"/* "$TARGET_FOLDER"/
            print_info "user TDS structure as follows:"
            tree "$TARGET_FOLDER"
            print_info "zTeX bundle has been installed successfully!"
            exit 0
            ;;
        \?)
            usage
            ;;
    esac
done
